### ISSUE TITLE
Can I get the Device IMEI with this package?

### ISSUE THREAD

**Issue by onehassan** [MaxGraey/fuse-device#5]

**Comment by MaxGraey** [comment]
Apple does not allow you to identify device rather than UUID, because IMEI or MAC-address is not a secure way to authenticate users, and raises privacy concerns. But on Android you can get IMEI using following code:

```java
TelephonyManager tm = (TelephonyManager)getSystemService(Context.TELEPHONY_SERVICE); 
tm.getDeviceId(); // return IMEI on GSM, MEID for CDMA
```

In this package I use this as a one part of building UUID on Android, but I use hashed value and UUID.nameUUIDFromBytes use intrnally MD5-hash for all simply hashed parts before creation final UUID, so this is some extent secure.
